# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 01:00
from __future__ import unicode_literals

import cases.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=cases.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 3, 1, 0, 18, 834312, tzinfo=utc), verbose_name='date comment created'),
        ),
    ]
