# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 00:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 1, 0, 42, 22, 845352, tzinfo=utc), verbose_name='last update date'),
        ),
        migrations.AlterField(
            model_name='case',
            name='open_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 1, 0, 42, 22, 844446, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 1, 0, 42, 22, 847034, tzinfo=utc), verbose_name='date comment created'),
        ),
    ]
