# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 01:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20170403_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 3, 1, 1, 30, 489711, tzinfo=utc), verbose_name='date comment created'),
        ),
    ]
